knpu_oauth2_client:
    clients:
        # configure your clients as described here: https://github.com/knpuniversity/oauth2-client-bundle#configuration
        fusionauth: 
            type: 'generic'
            provider_class: '\JerryHopper\OAuth2\Client\Provider\FusionAuth'
            client_id: '%env(CLIENT_ID)%'
            client_secret: '%env(CLIENT_SECRET)%'
            redirect_route: 'connect_fusionauth_check'
            provider_options: 
                urlAuthorize: '%env(FUSIONAUTH_BASE)%/oauth2/authorize'
                urlAccessToken: '%env(FUSIONAUTH_BASE)%/oauth2/token'
                urlResourceOwnerDetails: '%env(FUSIONAUTH_BASE)%/oauth2/userinfo'
